# Generated by Django 5.2.4 on 2025-08-21 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=500)),
                ('image_url', models.URLField(max_length=500)),
                ('title', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('expiration', models.CharField(max_length=100)),
                ('favorited_by', models.ManyToManyField(blank=True, related_name='favorite_jobs', through='scraper.Favorite', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='favorite',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.job'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['user', 'job'], name='scraper_fav_user_id_646e79_idx'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'job'), name='unique_user_job_favorite'),
        ),
    ]
